
project_id = "ocmwynwfqoxktdcebkac"

[functions.get-bill]
verify_jwt = true

[functions.get-bill-history]
verify_jwt = true

[functions.get-bill-versions]
verify_jwt = true

[functions.get-legislator]
verify_jwt = false

[functions.summarize-bill-changes]
verify_jwt = false

[functions.analyze-bill-newsworthiness]
verify_jwt = false
