// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ocmwynwfqoxktdcebkac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jbXd5bndmcW94a3RkY2Via2FjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMzk1MDQsImV4cCI6MjA1NzcxNTUwNH0.r5WOgW81g0jclyLFZMv0ycZISH4Wv9pEFugkhmPH0UQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);