// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tecsjzgesepxxlmopdnc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlY3Nqemdlc2VweHhsbW9wZG5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI0NzE4ODQsImV4cCI6MjA4ODA0Nzg4NH0.XpzH2vnP2JEuqf3D1kKVg3BKBdSxUhEZJZMyVE2EIww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});